USE TiendaVirtual;

--DROP PROCEDURE PS_GET_PRODUCTOS_CARRITO

 CREATE PROCEDURE PS_GET_PRODUCTOS_CARRITO 
	@IDUSUARIO INT
 AS
 BEGIN
     SELECT pr.NOMBRE, pr.PRECIO, pr.CANTIDAD, CR.CANTIDADCOMPRA
     FROM productos pr 
     INNER JOIN  
     CARRITO CR ON pr.IDPRODUCTO = CR.IDPRODUCTO 
     WHERE CR.ESTATUS = 1 AND CR.idusuario = @IDUSUARIO;
 END

 --SELECT * FROM CARRITO WHERE idusuario = 1

--EXEC PS_GET_PRODUCTOS_CARRITO 1


